import { useEffect, useState } from 'react'
import { useTranslation } from 'react-i18next'
import { Link } from 'react-router-dom'
import { LocationIcon } from '../icons/PatientHomeIcons'
import { getFeaturedDoctors, type FeaturedDoctor } from '../../services/doctorService'
import { APPOINTMENT_SEARCH_ROUTE, buildLoginPath } from '../../utils/navigation'
import { Reveal } from './Reveal'
import { LoadingState } from '../feedback/LoadingState'

export function FeaturedDoctorsSection() {
  const { i18n, t } = useTranslation(); const [doctors, setDoctors] = useState<FeaturedDoctor[]>([]); const [state, setState] = useState<'loading' | 'ready' | 'error'>('loading'); const [attempt, setAttempt] = useState(0)
  useEffect(() => { const controller = new AbortController(); getFeaturedDoctors(controller.signal).then((value) => { setDoctors(value); setState('ready') }).catch((error: unknown) => { if (error instanceof DOMException && error.name === 'AbortError') return; setState('error') }); return () => controller.abort() }, [attempt])
  const arabic = i18n.resolvedLanguage === 'ar'
  return <section className="bg-[var(--color-background)] py-16" id="featured-doctors"><div className="mx-auto max-w-7xl px-5 sm:px-8 lg:px-10"><Reveal><h2 className="text-3xl font-black sm:text-4xl">{t('publicHome.doctors.title')}</h2><p className="mt-3 text-[var(--color-text-secondary)]">{t('publicHome.doctors.description')}</p></Reveal>{state === 'loading' ? <div className="mt-8"><LoadingState message={t('publicHome.doctors.loading')} section /></div> : state === 'error' ? <div className="mt-8 rounded-2xl border border-[var(--color-border)] bg-white p-6 text-center"><p className="text-[var(--color-text-secondary)]" role="alert">{t('publicHome.doctors.loadError')}</p><button className="mt-4 min-h-11 rounded-full bg-[var(--color-primary)] px-5 font-bold text-white focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[var(--color-primary)]" onClick={() => { setState('loading'); setAttempt((value) => value + 1) }} type="button">{t('patient.home.retry')}</button></div> : doctors.length ? <div className="mt-8 grid gap-5 md:grid-cols-3">{doctors.map((doctor, index) => { const specialty = arabic ? doctor.specialization.name_ar : doctor.specialization.name_en; const location = arabic ? doctor.location.name_ar : doctor.location.name_en; const initials = doctor.name.split(' ').map((part) => part[0]).slice(0, 2).join(''); return <Reveal delay={index * 90} key={doctor.id}><article className="public-card rounded-3xl border border-[var(--color-border)] bg-white p-6 shadow-sm"><div className="flex items-center gap-4">{doctor.profile_image_url ? <img alt="" className="size-16 rounded-full object-cover" src={doctor.profile_image_url} /> : <div aria-hidden="true" className="grid size-16 shrink-0 place-items-center rounded-full bg-[var(--color-primary)] text-lg font-black text-white">{initials}</div>}<div><h3 className="text-xl font-bold">{doctor.name}</h3><p className="text-sm text-[var(--color-primary)]">{specialty}</p></div></div><p className="mt-5 flex items-center gap-2 text-sm text-[var(--color-text-secondary)]"><LocationIcon className="size-5 text-[var(--color-primary)]" />{location}</p><p className="mt-4 font-bold text-amber-600">★ {doctor.average_rating.toFixed(1)} <span className="font-normal text-[var(--color-text-secondary)]">({t('publicHome.doctors.reviewCount', { count: doctor.review_count })})</span></p><Link className="public-cta mt-6 block rounded-full bg-[var(--color-primary)] px-4 py-2.5 text-center font-bold text-white" to={buildLoginPath(APPOINTMENT_SEARCH_ROUTE)}>{t('publicHome.doctors.book')}</Link></article></Reveal> })}</div> : <p className="mt-8 rounded-2xl border border-[var(--color-border)] bg-white p-6 text-[var(--color-text-secondary)]">{t('publicHome.doctors.empty')}</p>}</div></section>
}
