import { useEffect, useState } from 'react'
import { useTranslation } from 'react-i18next'
import { Link } from 'react-router-dom'
import careTeam from '../../assets/home-carousel/care-team.jpg'
import surgery from '../../assets/home-carousel/surgical-care.jpg'
import technology from '../../assets/home-carousel/medical-technology.jpg'
import { APPOINTMENT_SEARCH_ROUTE, buildLoginPath } from '../../utils/navigation'

const slides = [{ key: 'access', image: careTeam }, { key: 'providers', image: surgery }, { key: 'wherever', image: technology }] as const

export function PublicHeroCarousel() {
  const { t } = useTranslation(); const [active, setActive] = useState(0); const [paused, setPaused] = useState(false)
  useEffect(() => { if (paused) return; const timer = window.setTimeout(() => setActive((value) => (value + 1) % slides.length), 5000); return () => window.clearTimeout(timer) }, [active, paused])
  return <section aria-label={t('publicHome.hero.label')} className="relative h-[30rem] overflow-hidden bg-slate-900 text-white sm:h-[32rem] lg:h-[36rem]" id="home" onFocusCapture={() => setPaused(true)} onBlurCapture={() => setPaused(false)} onMouseEnter={() => setPaused(true)} onMouseLeave={() => setPaused(false)}>{slides.map((slide, index) => <article aria-hidden={active !== index} className={`absolute inset-0 transition-opacity duration-700 motion-reduce:transition-none ${active === index ? 'opacity-100' : 'pointer-events-none opacity-0'}`} key={slide.key}><img alt={t(`publicHome.hero.slides.${slide.key}.alt`)} className="absolute inset-0 size-full object-cover" loading={index ? 'lazy' : 'eager'} src={slide.image}/><div className="absolute inset-0 bg-gradient-to-r from-slate-950/90 via-slate-900/65 to-slate-900/15 rtl:bg-gradient-to-l"/><div className="relative mx-auto flex h-full max-w-7xl items-center px-5 sm:px-8 lg:px-10"><div className="max-w-3xl"><p className="text-sm font-bold uppercase tracking-[0.16em] text-teal-200">{t('publicHome.hero.eyebrow')}</p><h1 className="mt-4 text-4xl font-black leading-tight sm:text-5xl lg:text-6xl">{t(`publicHome.hero.slides.${slide.key}.title`)}</h1><p className="mt-5 max-w-2xl text-lg leading-relaxed text-white/90">{t(`publicHome.hero.slides.${slide.key}.description`)}</p><div className="mt-8 flex flex-wrap gap-3"><a className="public-cta rounded-full bg-[var(--color-primary)] px-6 py-3 font-bold text-white hover:bg-[#0F766E]" href="#featured-doctors">{t('publicHome.hero.findDoctor')}</a><Link className="public-cta rounded-full border border-white/70 bg-white/10 px-6 py-3 font-bold text-white backdrop-blur hover:bg-white/20" to={buildLoginPath(APPOINTMENT_SEARCH_ROUTE)}>{t('publicHome.hero.login')}</Link></div></div></div></article>)}<div aria-label={t('publicHome.hero.pagination')} className="absolute inset-x-0 bottom-6 z-10 flex justify-center gap-2" role="group">{slides.map((slide,index)=><button aria-label={t('publicHome.hero.showSlide',{number:index+1})} aria-pressed={active===index} className={`h-2.5 rounded-full border border-white transition ${active===index?'w-8 bg-white':'w-2.5 bg-white/40'}`} key={slide.key} onClick={()=>setActive(index)} type="button"/>)}</div></section>
}
