import { useEffect, useState } from 'react'
import { useTranslation } from 'react-i18next'
import { useNavigate, useSearchParams } from 'react-router-dom'
import { DoctorResultCard } from '../../components/patient/DoctorResultCard'
import { ErrorState } from '../../components/feedback/ErrorState'
import { LoadingState } from '../../components/feedback/LoadingState'
import { ChevronIcon } from '../../components/icons/PatientHomeIcons'
import { ApiError } from '../../services/apiClient'
import { searchDoctors, type DoctorSummary } from '../../services/doctorService'
import { PublicLayout } from '../../layouts/PublicLayout'
import { buildLoginPath } from '../../utils/navigation'

export function DoctorSearchResultsPage() {
  const { t } = useTranslation(); const navigate = useNavigate(); const [params] = useSearchParams()
  const [doctors, setDoctors] = useState<DoctorSummary[]>([]); const [state, setState] = useState<'loading'|'success'|'error'>('loading'); const [attempt, setAttempt] = useState(0); const [notice, setNotice] = useState('')
  const specialization = params.get('specialization') ?? ''; const location = params.get('location') ?? ''; const availability = params.get('availability') === 'week' ? 'week' : 'today'

  useEffect(() => { if (!specialization || !location) { navigate('/patient/doctors/search', { replace: true }); return } let active = true; searchDoctors({ specialization, location, availability }).then((response) => { if (!active) return; setDoctors(response.data.doctors); setState('success') }).catch((error: unknown) => { if (!active) return; if (error instanceof ApiError && (error.status === 401 || error.status === 403)) navigate(buildLoginPath(`/patient/doctors/results?${params.toString()}`), { replace: true }); else setState('error') }); return () => { active = false } }, [attempt, availability, location, navigate, params, specialization])
  return <PublicLayout>{state === 'loading' ? <LoadingState contained message={t('patient.searchResults.loading')} /> : state === 'error' ? <ErrorState contained message={t('patient.searchResults.error')} retryLabel={t('patient.home.retry')} onRetry={() => { setState('loading'); setAttempt((value) => value + 1) }} /> : <div className="bg-[var(--color-background)] px-5 py-8 sm:px-8 sm:py-12"><section className="mx-auto max-w-5xl"><header className="flex items-center justify-between gap-3"><button aria-label={t('patient.searchResults.back')} className="grid size-12 shrink-0 place-items-center rounded-full border border-[var(--color-border)] bg-white text-[var(--color-primary)] transition hover:border-[var(--color-primary)] focus-visible:outline-2 focus-visible:outline-[var(--color-primary)]" onClick={() => navigate('/patient/doctors/search')} type="button"><ChevronIcon className="size-6 rtl:rotate-180" /></button><div className="min-w-0 flex-1 text-center"><h1 className="text-2xl font-extrabold sm:text-3xl">{t('patient.searchResults.title')}</h1><p className="mt-1 text-sm text-[var(--color-text-secondary)]">{t('patient.searchResults.found', { count: doctors.length })}</p></div><span aria-hidden="true" className="size-12" /></header>{doctors.length ? <div className="mt-8 grid gap-5 md:grid-cols-2">{doctors.map((doctor, index) => <div className="service-card-enter" key={doctor.id} style={{ animationDelay: `${index * 70}ms` }}><DoctorResultCard doctor={doctor} onViewProfile={() => setNotice(t('patient.searchResults.profilePending'))} /></div>)}</div> : <div className="mt-12 rounded-3xl border border-[var(--color-border)] bg-white p-10 text-center shadow-sm"><h2 className="text-xl font-bold">{t('patient.searchResults.emptyTitle')}</h2><p className="mt-2 text-[var(--color-text-secondary)]">{t('patient.searchResults.emptyDescription')}</p><button className="mt-6 rounded-full bg-[var(--color-primary)] px-6 py-3 font-bold text-white transition hover:-translate-y-0.5 hover:bg-[#0F766E] focus-visible:outline-2 focus-visible:outline-[var(--color-primary)]" onClick={() => navigate('/patient/doctors/search')} type="button">{t('patient.searchResults.changeFilters')}</button></div>}<p aria-live="polite" className="mt-5 min-h-6 text-center text-sm text-[var(--color-primary)]">{notice}</p></section></div>}</PublicLayout>
}
