import { useEffect, useState } from 'react'
import { useTranslation } from 'react-i18next'
import { useNavigate } from 'react-router-dom'
import { ErrorState } from '../../components/feedback/ErrorState'
import { LoadingState } from '../../components/feedback/LoadingState'
import { CalendarIcon } from '../../components/icons/PatientHomeIcons'
import { PatientLayout } from '../../layouts/PatientLayout'
import { PublicLayout } from '../../layouts/PublicLayout'
import { ApiError } from '../../services/apiClient'
import { logout } from '../../services/authService'
import { getPatientAppointments, type PatientAppointment } from '../../services/patientAppointmentService'
import { SUDAN_TIME_ZONE } from '../../utils/dateTime'
import { buildLoginPath } from '../../utils/navigation'

type LoadState = 'loading' | 'success' | 'error'

export function PatientAppointmentsPage() {
  const { i18n, t } = useTranslation(); const navigate = useNavigate()
  const [appointments, setAppointments] = useState<PatientAppointment[]>([]); const [state, setState] = useState<LoadState>('loading'); const [attempt, setAttempt] = useState(0); const [loggingOut, setLoggingOut] = useState(false)
  useEffect(() => { const controller = new AbortController(); getPatientAppointments(controller.signal).then((data) => { setAppointments(data); setState('success') }).catch((error: unknown) => { if (error instanceof DOMException && error.name === 'AbortError') return; if (error instanceof ApiError && (error.status === 401 || error.status === 403)) navigate(buildLoginPath('/patient/appointments'), { replace: true }); else setState('error') }); return () => controller.abort() }, [attempt, navigate])
  async function signOut() { setLoggingOut(true); try { await logout(); navigate('/login', { replace: true }) } catch { setLoggingOut(false) } }
  const locale = i18n.resolvedLanguage === 'ar' ? 'ar-SD' : 'en'
  const now = new Date(); const upcoming = appointments.filter((item) => item.status === 'confirmed' && new Date(item.ends_at) >= now); const previous = appointments.filter((item) => item.status === 'confirmed' && new Date(item.ends_at) < now); const completed = appointments.filter((item) => item.status === 'completed'); const cancelled = appointments.filter((item) => item.status === 'cancelled')
  const card = (appointment: PatientAppointment) => { const start = new Date(appointment.starts_at); const date = new Intl.DateTimeFormat(locale, { dateStyle: 'medium', timeZone: SUDAN_TIME_ZONE }).format(start); const time = new Intl.DateTimeFormat(locale, { timeStyle: 'short', timeZone: SUDAN_TIME_ZONE }).format(start); const specialty = i18n.resolvedLanguage === 'ar' ? appointment.doctor.specialization.name_ar : appointment.doctor.specialization.name_en; const reviewAction = appointment.status === 'completed'; return <article className="rounded-3xl border border-[var(--color-border)] bg-white p-5 shadow-sm transition hover:-translate-y-0.5 hover:border-teal-200 hover:shadow-md motion-reduce:transform-none" key={appointment.id}><div className="flex items-start justify-between gap-4"><div className="min-w-0"><h3 className="truncate text-lg font-extrabold">{appointment.doctor.name}</h3><p className="mt-1 text-sm font-semibold text-[var(--color-primary)]">{specialty}</p></div><span className={`rounded-full px-3 py-1 text-xs font-bold ${appointment.status === 'cancelled' ? 'bg-slate-100 text-slate-600' : 'bg-[var(--color-success-surface)] text-emerald-800'}`}>{t(`patient.appointments.statuses.${appointment.status}`)}</span></div><dl className="mt-5 grid grid-cols-2 gap-3 border-t border-[var(--color-border)] pt-4"><div><dt className="text-xs font-bold text-[var(--color-text-secondary)]">{t('patient.appointments.date')}</dt><dd className="mt-1 font-semibold">{date}</dd></div><div><dt className="text-xs font-bold text-[var(--color-text-secondary)]">{t('patient.appointments.time')}</dt><dd className="direction-ltr mt-1 font-semibold">{time}</dd></div></dl><button className="mt-5 w-full rounded-full border border-[var(--color-primary)] px-4 py-2.5 font-bold text-[var(--color-primary)] hover:bg-[var(--color-primary-surface)] focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[var(--color-primary)]" onClick={() => navigate(reviewAction ? `/patient/appointments/${appointment.id}/review` : `/patient/appointments/${appointment.id}`)} type="button">{t(reviewAction ? appointment.review ? 'patient.appointments.viewReview' : 'patient.appointments.rateDoctor' : 'patient.appointments.viewDetails')}</button></article> }
  const section = (key: 'upcoming' | 'previous' | 'completed' | 'cancelled', items: PatientAppointment[]) => <section className="mt-8" aria-labelledby={`patient-${key}`}><div className="flex items-center justify-between gap-3"><h2 className="text-2xl font-extrabold" id={`patient-${key}`}>{t(`patient.appointments.sections.${key}`)}</h2><span className="rounded-full bg-[var(--color-primary-surface)] px-3 py-1 text-sm font-bold text-[var(--color-primary)]">{items.length}</span></div>{items.length ? <div className="mt-4 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{items.map(card)}</div> : <div className="mt-4 rounded-3xl border border-dashed border-[var(--color-border)] bg-white p-7 text-center text-[var(--color-text-secondary)]">{t(`patient.appointments.empty.${key}`)}</div>}</section>
  if (state === 'loading') return <PublicLayout><LoadingState contained message={t('patient.appointments.loading')} /></PublicLayout>
  if (state === 'error') return <PublicLayout><ErrorState contained message={t('patient.appointments.error')} onRetry={() => { setState('loading'); setAttempt((value) => value + 1) }} retryLabel={t('patient.home.retry')} /></PublicLayout>
  return <PatientLayout activeSection="appointments" isLoggingOut={loggingOut} onAppointments={() => undefined} onDashboard={() => navigate('/patient/home')} onLogout={signOut} onProfile={() => navigate('/patient/profile')}><div className="mx-auto max-w-7xl px-5 py-8 sm:px-8 lg:px-10"><header className="rounded-3xl border border-teal-100 bg-gradient-to-r from-[var(--color-primary-surface)] to-white p-6 rtl:bg-gradient-to-l sm:p-8"><CalendarIcon className="size-9 text-[var(--color-primary)]" /><h1 className="mt-3 text-3xl font-extrabold sm:text-4xl">{t('patient.appointments.title')}</h1><p className="mt-2 max-w-3xl text-[var(--color-text-secondary)]">{t('patient.appointments.description')}</p></header>{section('upcoming', upcoming)}{section('previous', previous)}{section('completed', completed)}{section('cancelled', cancelled)}</div></PatientLayout>
}
