import { useTranslation } from 'react-i18next'
import type { CompletionItemKey, ProfileCompletionResult } from '../../utils/profileCompletion'

interface Props { completion: ProfileCompletionResult; onMissingItem?: (item: CompletionItemKey) => void }

export function ProfileCompletion({ completion, onMissingItem }: Props) {
  const { t } = useTranslation(); const complete = completion.percentage === 100; const visibleMissing = completion.missing.slice(0, 3)
  return <section aria-label={t('profileCompletion.label')} className="rounded-3xl border border-teal-100 bg-[var(--color-primary-surface)] p-5 shadow-sm sm:p-6"><div className="flex flex-col items-center gap-5 sm:flex-row sm:items-start"><div className="relative size-24 shrink-0" role="img" aria-label={t('profileCompletion.percentComplete', { percentage: completion.percentage })}><svg aria-hidden="true" className="size-full -rotate-90" viewBox="0 0 42 42"><circle className="fill-none stroke-slate-200" cx="21" cy="21" pathLength="100" r="17" strokeWidth="4" /><circle className="fill-none stroke-[var(--color-primary)] transition-[stroke-dashoffset] duration-700 motion-reduce:transition-none" cx="21" cy="21" pathLength="100" r="17" strokeDasharray="100" strokeDashoffset={100 - completion.percentage} strokeLinecap="round" strokeWidth="4" /></svg><span className="absolute inset-0 grid place-items-center text-lg font-black text-[var(--color-primary)]">{completion.percentage}%</span></div><div className="min-w-0 flex-1 text-center sm:text-start"><h2 className="text-xl font-extrabold">{t(complete ? 'profileCompletion.completeTitle' : 'profileCompletion.title')}</h2><p className="mt-1 text-sm font-semibold text-[var(--color-text-secondary)]">{t('profileCompletion.summary', { completed: completion.completed, total: completion.total })}</p>{!complete && <ul className="mt-4 flex flex-wrap justify-center gap-2 sm:justify-start">{visibleMissing.map((item) => <li key={item}>{onMissingItem ? <button className="rounded-full border border-teal-200 bg-white px-3 py-1.5 text-sm font-bold text-[var(--color-primary)] transition hover:border-[var(--color-primary)] focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[var(--color-primary)]" onClick={() => onMissingItem(item)} type="button">{t(`profileCompletion.items.${item}`)}</button> : <span className="inline-block rounded-full border border-teal-200 bg-white px-3 py-1.5 text-sm font-bold text-[var(--color-primary)]">{t(`profileCompletion.items.${item}`)}</span>}</li>)}</ul>}</div></div></section>
}
